name: Flask CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Repository Code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.1.0'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Flask App Check
        run: |
          python app.py